### ISSUE TITLE
BPEL - má volat 2 služby, nejen jednu

### ISSUE THREAD

**Issue by jakubklimek** [lhotanok/web-services#1]
BPEL - má volat 2 služby, nejen jednu

**Comment by lhotanok** [comment]
@jakubklimek 
V rámci BPEL se teď kromě `trip:TripPlannerService` volá také služba `event:EventDiscoveryApiService`: https://github.com/lhotanok/web-services/pull/2

Takto je to v pořádku, nebo je potřeba nějaká úprava?

**Comment by jakubklimek** [comment]
Tak... je to volání 2 operací jedné služby, nikoliv volání dvou služeb, ale už to nechme. OK
